# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaltura VPaaS
email: community@kaltura.com
description: > # this means to ignore newlines until "baseurl:"
  Kaltura VPaaS is... content goes here
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vpass.kaltura.com" # the base hostname & protocol for your site
twitter_username: kaltura
github_username:  kaltura
permalink: none

# Build settings
markdown: kramdown
timezone: America/New_York
lsi: true
#incremental: true
