# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaltura VPaaS
email: community@kaltura.com
description: > # this means to ignore newlines until "baseurl:"
  Kaltura VPaaS is... content goes here
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://54.161.130.174" # the base hostname & protocol for your site
twitter_username: kaltura
github_username:  kaltura
permalink: none
highlighter: rouge
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#markdown: redcarpet

redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
timezone: America/New_York
lsi: true
#incremental: true
#gems:
#  - jekyll-git_metadata
gems:
    - jekyll-sitemap
