# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaltura VPaaS - Video Platform as a Service
email: community@kaltura.com
description: > # this means to ignore newlines until "baseurl:"
      Cloud video services and SDKs for everything video. All devices; All media workflows; All applications. Powering Any Video Experience. Pay as you go. 
baseurl: "" # the subpath of your site, e.g. /blog
domain: "vpaas.kaltura.com"
url: "https://vpaas.kaltura.com" # the base hostname & protocol for your site
#url: "http://localhost:8888" # the base hostname & protocol for your site
twitter_username: kaltura
github_username:  kaltura
permalink: none
highlighter: rouge
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#markdown: redcarpet

redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
timezone: America/New_York
lsi: true
#incremental: true
gems:
   - jekyll-plantuml
#  - jekyll-git_metadata
#    - jekyll-sitemap
